### PR TITLE
Prepare for JOSS submittal

### PR DESCRIPTION
**Pull request by noamross**
This should add everything required for submittal to JOSS, including:

- A vignette with an airline-related examples and some discussion of performance
- A `paper.md` (can be previewed as PDF if you install `noamross/rticles@joss`)
- A bunch of little things for CRAN-specific checks
- Running on r-hub for CRAN gotchas

There is one API change, which now allows users to determine which columns are used for `from`, `to`, and `weights`.  They are the first and second columns and a column names "weight" by default.  I found this was a good default in hunting around for different data sets to use for examples - it lets you use many **igraph** objects without any more manipulation. See the vignette for an example.  

Go over any text and make any changes or reversions to code that you want but I suggest submitting ASAP while the iron is hot.  If asked for reviewers `michaellevy` is a possibility, as are folks involved in `igraph` and `tidygraph`.

### CODE REVIEW

**Comment by noamross** [comment]
I briefly considered a six-degrees-of-kevin-bacon example, but pulling the IMDB data was too involved.  We will leave it as an exercise for the reader.

**Comment by toph-allen** [comment]
All these changes look good, except for that I can't build `using-yenpathy.Rmd`.

On all the `bench::mark` function calls, I get the following error:

```
Error: Can't slice a scalar
> traceback()
14: vec_slice(result, i)
13: slice_df(x, i, j, drop = drop)
12: `[.tbl_df`(x, seq_len(n), , drop = FALSE)
11: NextMethod("[")
10: unique(c("bench_mark", class(x)))
9: bench_mark(NextMethod("["))
8: `[.bench_mark`(x, seq_len(n), , drop = FALSE)
7: x[seq_len(n), , drop = FALSE]
6: head.data.frame(x, max.print)
5: head(x, max.print)
4: as.data.frame(head(x, max.print))
3: overridePrint(o$x, o$options, o$className, o$nRow, o$nCol)
2: print.tbl_df(x)
1: (function (x, ...) 
   UseMethod("print"))(x)
```

I'm having some issues updating Rcpp packages, though, so I could just have something off with my R installation. I'm trying to fix it now.

**Comment by noamross** [comment]
Given that `bench` was updated a week ago and it and its dependencies do low-level stuff it's probably out-of-date-dependencies.

**Comment by toph-allen** [comment]
Ok, I got this to run on Prospero, so (1) there’s definitely some issue on my laptop and (2) it looks good to go. All of the changes are great.

One last question: should we tidy up some of the scratch files in the `data-raw` directory for the release? I’m fine just deleting them, unless there’s some good place to shove old scratch files.

**Comment by toph-allen** [comment]
Wait, actually, there was something I was experiencing on my laptop where the shortest paths found by the different packages used in the vignette were different from `yenpathy`’s. I checked on one of the test graphs in data-raw where I *know* the shortest paths, and `yenpathy` was correct, so I’m not sure what the discrepancy is.

**Comment by toph-allen** [comment]
I want to mull over the API name changes. For example, `all_simple_paths()` and `shortest_path()` from `igraph` use `from` and `to` for its start and end vertices, and this legitimately confused me.

We could use `from` and `to` for the start and end vertex, and `from_col` and `to_col` (or `col_from` and `col_to`) to specify the columns.

**Comment by noamross** [comment]
I like your suggested name changes.

Yes, let's clear out the data-raw directory.  You can just delete it. All the scripts there have been ported to `tests/`.  Unless you want to document `730.csv` as package data and use in a vignette/test/example, I'd get rid of it.

**Comment by toph-allen** [comment]
I deleted the scratch directory, because the `730.tsv` is a test file from the original C++ repo and we can adapt it from there again if need be.

I'm happy with this now, with the API updates.

**Pull request merged**
